#!/bin/sh
# entrypoint.sh — Railway startup script
# Writes config/config.toml from environment variables before launching the MCP server.
# config.toml is gitignored (it contains secrets), so we generate it at container start.

set -e

CONFIG_PATH="config/config.toml"

echo "[entrypoint] Writing ${CONFIG_PATH} from environment variables..."

cat > "${CONFIG_PATH}" << EOF
# Auto-generated by entrypoint.sh at container startup — do not edit manually.

[llm]
model       = "${LLM_MODEL}"
base_url    = "${LLM_BASE_URL}"
api_key     = "${LLM_API_KEY}"
api_type    = "openai"
api_version = ""
max_tokens  = 8192
temperature = 0.0

[llm.vision]
model       = "${LLM_MODEL}"
base_url    = "${LLM_BASE_URL}"
api_key     = "${LLM_API_KEY}"
api_type    = "openai"
api_version = ""
max_tokens  = 8192
temperature = 0.0

[mcp]
server_reference = "app.mcp.server"

[browser]
headless         = true
disable_security = true

[runflow]
use_data_analysis_agent = false
EOF

echo "[entrypoint] config.toml written. Starting MCP server..."
exec python run_mcp_server.py --transport stdio
